[catalogs]
searchPriorities = []
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.effects'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.emoji'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.recents'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.smart-folders'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.windows'

        [catalogs.globalScopes.scope]
        kind = 'none'

[[comboMode.bindings]]
key = '/'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Library/CoreServices/Finder.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '2'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Mail.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '3'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Phone.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '4'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Copilot.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '8'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Passwords.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '9'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Contacts.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'a'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'b'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Google Chrome.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'c'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Calendar.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'd'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Discord.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'e'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Mail.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'f'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Users/chris/Applications/Facebook.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'h'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Users/chris/Applications/Line6/Helix Stadium.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'i'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Music.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'j'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Journal.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'k'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Lens.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'm'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Messages.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'n'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Notes.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'o'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/OrbStack.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'r'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Reminders.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 's'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Slack.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 't'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/TablePlus.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'u'
label = 'Unifi'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open-url'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'url:raycast-x://extensions/lewj/unifi/open-dashboard' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'v'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Visual Studio Code.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'x'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Expressions.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'y'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Users/chris/Applications/YouTube.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'z'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/zoom.us.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'g'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/run-text-as-shell-command'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'text:' ]
        type = 'savedCommand'

[hotkeys]
custom = []

    [hotkeys.app.comboMode]
    carbonKeyCode = 37
    carbonModifiers = 6912

[settings]
appPresentationMode = 'never'
comboModeThemeStyle = 'cheatsheet'
physicalHyperKeyQuickPressBehavior = 'triggersEscape'
physicalHyperKeySource = 'capsLock'
shelfAutoCloseWhenTasksComplete = true
textModeTriggerType = 'disabled'
