brew "docker"
brew "node"
brew "firebase-cli"
brew "fish"
brew "gh"
brew "git"
brew "gitoxide"
brew "go"
brew "helm"
brew "htop"
brew "k6"
brew "k9s"
brew "kubecolor"
brew "kubernetes-cli"
brew "python@3.14"
brew "mas"
brew "pkgconf"
brew "pnpm"
brew "pulumi"
brew "python@3.13"
brew "ruby"
brew "rust"
brew "xh"
brew "zsh"
cask "camo-studio"
cask "choosy"
cask "copilot-money"
cask "dash"
cask "discord"
cask "expressions"
cask "gcloud-cli"
cask "google-chrome"
cask "hammerspoon"
cask "hdhomerun"
cask "insomnia"
cask "istat-menus"
cask "kaleidoscope"
cask "karabiner-elements"
cask "kiro-cli"
cask "leader-key"
cask "lens"
cask "logi-options+"
cask "logitech-g-hub"
cask "orbstack"
cask "plex"
cask "proxyman"
cask "qflipper"
cask "raspberry-pi-imager"
cask "raycast"
cask "slack"
cask "steam"
cask "tableplus"
cask "twingate"
cask "viscosity"
cask "visual-studio-code"
cask "warp"
cask "wifi-explorer"
cask "wifiman"
cask "zoom"
mas "1Blocker", id: 1365531024
mas "Deliveries", id: 290986013
mas "Flighty", id: 1358823008
mas "HomeControl", id: 1547121417
mas "Homie", id: 1533590432
mas "iCircuit", id: 454347770
mas "Logic Pro", id: 634148309
mas "Mapper", id: 1589391989
mas "Numbers", id: 361304891
mas "Raycast Companion", id: 6738274497
mas "Xcode", id: 497799835
vscode "bbenoist.nix"
vscode "bennycode.sort-everything"
vscode "britesnow.vscode-toggle-quotes"
vscode "dbaeumer.vscode-eslint"
vscode "deerawan.vscode-dash"
vscode "dnicolson.binary-plist"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "ezzak.current-path"
vscode "formulahendry.code-runner"
vscode "github.vscode-github-actions"
vscode "hangxingliu.vscode-nginx-conf-hint"
vscode "idleberg.applescript"
vscode "idleberg.jxa"
vscode "jock.svg"
vscode "johnreemar.vscode-qwik-snippets"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "naumovs.color-highlight"
vscode "pustelto.bracketeer"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "sammcleod.ghostty-config-syntax"
vscode "sidneys1.gitconfig"
vscode "stylelint.vscode-stylelint"
vscode "subframe7536.custom-ui-style"
vscode "sumneko.lua"
vscode "swiftlang.swift-vscode"
vscode "syler.ignore"
vscode "tamasfe.even-better-toml"
vscode "that70schris.arcade"
vscode "tonka3000.raycast"
vscode "unifiedjs.vscode-mdx"
vscode "vadimcn.vscode-lldb"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "wangwindow.quick-open-in-new-window"
vscode "zongou.vs-seti-hacknerdfont"
