./**/*.{s[ac]ss,css}: stylelint --fix
# ./**/*.jso*: prettier --write --ignore-path false
./**/*.*ml: prettier --write --ignore-path false
./**/*.[cm][jt]s: eslint --fix
./**/*.[jt]sx: eslint --fix
./**/*.[jt]s: eslint --fix
