./**/*.jso*: prettier --write --ignore-path *lock*
./**/*.*ml: prettier --write --ignore-path *lock*
./**/*.{s[ac]ss,css}: stylelint --fix
./**/*.[cm][jt]s: eslint --fix
./**/*.[jt]sx: eslint --fix
./**/*.[jt]s: eslint --fix
