alignComments: false
arrayAutoCollapse: false
indentEntries: true
reorderKeys: true
trailingComma: all
singleQuote: true
semi: false
ignorePath: false
plugins:
  - prettier-plugin-toml
  - '@prettier/plugin-xml'
