#https-listen-port: 443
disable:
  - traefik
tls-san:
  - 192.168.0.5
  - bailey.mx
  - berry
  - berry.bailey.mx
  - berry.home
  - berry.local
  - kube.berry.home
  - kubernetes.default.svc.cluster.local
