hs.console.clearConsole()
hs.allowAppleScript(true)
hs.loadSpoon('clear')
hs.loadSpoon('enter')
hs.loadSpoon('escape')
hs.loadSpoon('finder')
hs.loadSpoon('Hammerflow')
spoon.Hammerflow.loadFirstValidTomlFile({
  'flow.toml',
})
