'$schema' = 'https://starship.rs/config-schema.json'
format = """
$username($hostname/)\
$directory\
$git_branch\
$git_commit\
$package\
$git_state\
$git_status\
$git_metrics\
$fill \
$swift\
$python\
$docker_context\
$container\
$helm\
$kubernetes\
$pulumi\
$terraform\
$gcloud\
$rust\
$sudo\
$shell\
$os\
"""

palette = 'arcade'
[palettes.arcade]
  black = '#777777'
  blue = '#3399ff'
  cyan = '#00bbdd'
  green = '#77ff88'
  magenta = '#aa88ff'
  red = '#ff4444'
  white = '#eeeeee'
  yellow = '#eeff77'
  bright-black = '#999999'
  bright-blue = '#99eeff'
  bright-cyan = '#33ccee'
  bright-green = '#00ff44'
  bright-magenta = '#eeaaff'
  bright-red = '#ff0000'
  bright-white = '#ffffff'
  bright-yellow = '#ffff00'

[directory]
  format = '[$path]($style)[$read_only]($read_only_style) '
  read_only_style = 'bright-yellow'
  read_only = ' 󰌾'
  style = '#cccccc'
  truncate_to_repo = false
  truncation_length = 5
  repo_root_style = 'blue'
  repo_root_format = """
[$before_root_path]($before_repo_root_style) \
[$repo_root]($repo_root_style)[$path]($style)\
[$read_only]($read_only_style) \
"""

[docker_context]
  format = '  [$context]($style)'
  style = '#2460ff'

[fill]
  style = '#999999 bold'
  symbol = '⎯' #u23af

  # dashline:
  # symbol = '―' #u2015
  # symbol = '—' #u2014
  # symbol = '–' #u2013
  # symbol = '‒' #u2012
  # symbol = '‑' #u2011
  # symbol = '‐' #u2010

  # off center:
  # symbol = '─' #u2500
  # symbol = '' #nf45b

[gcloud]
  format = '( ☁️ [$project]($style))'
  style = '#1a73e8'

[git_branch]
  format = '[\($branch(:$remote_branch)\)]($style) '
  only_attached = true
  style = '#f1502f'

[git_commit]
  format = '[\($hash($tag)\)]($style) '
  style = '#f1502f'
  tag_disabled = false

[git_metrics]
  disabled = false
  format = """
([$added](green) )\
([$deleted](red) )\
"""

[git_state]
  format = """
\\([$state(\
$progress_current/\
$progress_total)]\
($style)\
\\) """

[git_status]
  conflicted = '= '
  ahead = '[](purple) '
  behind = '[](purple) '
  diverged = '[](purple) '
  untracked = '[▪︎](black) '
  deleted = '[✘](red) '
  renamed = '[⏩︎](white) '
  staged = '[⭑](yellow) '
  stashed = '[\$](yellow) '
  format = """
$stashed\
$ahead_behind\
$conflicted\
$renamed\
$deleted\
$staged\
$untracked\
"""

[hostname]
  format = '@[$hostname]($style)'
  style = 'green'

[kubernetes]
  disabled = false
  format = " 󰠳 [$context(/$namespace)]($style)"
  style = '#09c1d1'

[lua]
  symbol = ' '

[nix_shell]
  symbol = ' '

[package]
  format = '📦 [$version]($style) '
  version_format = '$raw'
  style = 'white'

[pulumi]
  format = '  [$stack]($style)'
  style = '#be5188'

[python]
  symbol = ' '

[ruby]
  symbol = ' '

[rust]
  symbol = '󱘗 '

[shell]
  disabled = false
  format = ' > [$indicator]($style)'
  style = 'yellow'

[sudo]
  disabled = false
  format = ' 👻'

[swift]
  symbol = ' '

[username]
  format = '[$user]($style)'
  style_user = 'yellow'
  style_root = 'red'

[os]
  disabled = false
  format = ' [$symbol]($style) '
  style = 'white'

[os.symbols]
  Alpine = ''
  Arch = ''
  Artix = ''
  Debian = '󰣚'
  Fedora = '󰮤'
  Linux = ''
  Macos = ''
  NixOS = ''
  Raspbian = ''
  Redhat = '󱄛'
  Ubuntu = ''
  Unknown = '?'
  Windows = '󰍲'
