'$schema' = 'https://starship.rs/config-schema.json'
format = """
$username($hostname/)\
$directory\
$git_branch\
$git_commit\
$package\
$git_state\
$git_status\
$git_metrics\
$fill \
$docker_context\
$container\
$gcloud\
$helm\
$kubernetes\
$pulumi\
$python\
$rust\
$swift\
$terraform\
$sudo\
$shell\
$os\
"""

palette = 'arcade'
[palettes.arcade]
  black = '#777777'
  blue = '#3399ff'
  bright-black = '#999999'
  bright-blue = '#99eeff'
  bright-cyan = '#33ccee'
  bright-green = '#00ff44'
  bright-magenta = '#eeaaff'
  bright-red = '#ff0000'
  bright-white = '#ffffff'
  bright-yellow = '#ffff00'
  cyan = '#00bbdd'
  green = '#77ff88'
  magenta = '#aa88ff'
  red = '#ff4444'
  white = '#eeeeee'
  yellow = '#eeff77'

[directory]
  format = '[$path]($style)[$read_only]($read_only_style) '
  read_only = ' 󰌾'
  read_only_style = 'bright-yellow'
  repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)[$path]($style)\
[$read_only]($read_only_style) \
"""
  repo_root_style = 'blue'
  style = '#cccccc'
  truncate_to_repo = false
  truncation_length = 5

[docker_context]
  format = ' $symbol[$context]($style)'
  style = '#2460ff'
  symbol = ' '

[fill]
  style = '#999999'
  symbol = '⎯' #u23af

  # consistent:
  # symbol = '' #ueacc
  # symbol = '‐' #u2010
  # symbol = '‑' #u2011
  # symbol = '‒' #u2012
  # symbol = '–' #u2013
  # symbol = '—' #u2014
  # symbol = '―' #u2015

  # off center:
  # symbol = '─' #u2500
  # symbol = '━' #u2501
  # symbol = '' #nf45b
  # symbol = '' #uf48b
  # symbol = '﹣' #uFE63
  # symbol = '－' #uFF0D

[gcloud]
  format = '( $symbol[$project]($style))'
  style = '#1a73e8'
  symbol = '☁️ '

[git_branch]
  format = '[\($branch(:$remote_branch)\)]($style) '
  only_attached = true
  style = '#f1502f'

[git_commit]
  format = '[\($hash($tag)\)]($style) '
  style = '#f1502f'
  tag_disabled = false

[git_metrics]
  disabled = false
  format = """
([$added](green) )\
([$deleted](red) )\
"""

[git_state]
  format = """
\\([$state(\
$progress_current/\
$progress_total)]\
($style)\
\\) """

[git_status]
  ahead = '[](purple) '
  behind = '[](purple) '
  conflicted = '= '
  deleted = '[✘](red) '
  diverged = '[](purple) '
  format = """
$stashed\
$ahead_behind\
$conflicted\
$renamed\
$deleted\
$staged\
$untracked\
"""
  renamed = '[⏩︎](white) '
  staged = '[⭑](yellow) '
  stashed = '[\$](yellow) '
  untracked = '[▪︎](black) '

[hostname]
  format = '@[$hostname]($style)'
  style = 'green'

[kubernetes]
  disabled = false
  format = ' $symbol[$context(/$namespace)]($style)'
  style = '#09c1d1'
  symbol = '󰠳 '

[lua]
  symbol = ' '

[nix_shell]
  symbol = ' '

[package]
  format = '$symbol[$version]($style) '
  style = 'white'
  symbol = '📦 '
  version_format = '$raw'

[pulumi]
  format = ' $symbol[$stack]($style)'
  style = '#be5188'
  symbol = ' '

[python]
  symbol = ' '

[ruby]
  symbol = ' '

[rust]
  format = ' $symbol[$version]($style)'
  style = '#d64b21'
  symbol = ' '

[shell]
  disabled = false
  format = '  [$indicator]($style)'
  style = 'yellow'

[sudo]
  disabled = false
  format = ' 👻'

[swift]
  symbol = '󰛥 '

[username]
  format = '[$user]($style)'
  style_root = 'red'
  style_user = 'yellow'

[os]
  disabled = false
  format = ' [$symbol]($style)'
  style = 'white'

[os.symbols]
  Alpine = ' '
  Amazon = ' '
  Android = ' '
  Arch = ' '
  Artix = ' '
  Bluefin = ' '
  CachyOS = ' '
  CentOS = ' '
  Debian = ' '
  DragonFly = ' '
  Elementary = ' '
  Emscripten = ' '
  EndeavourOS = ' '
  Fedora = ' '
  FreeBSD = ' '
  Garuda = ' '
  Gentoo = ' '
  HardenedBSD = '󰞌 '
  Illumos = ' '
  InstantOS = ' '
  Ios = '󰀷 '
  Kali = ' '
  Linux = ' '
  Mabox = ' '
  Macos = ' '
  Manjaro = ' '
  Mariner = ' '
  MidnightBSD = ' '
  Mint = ' '
  NetBSD = ' '
  NixOS = ' '
  Nobara = ' '
  OracleLinux = '󰺡 '
  PikaOS = ' '
  Pop = ' '
  Raspbian = ' '
  RedHatEnterprise = '󱄛 '
  Redhat = '󱄛 '
  Redox = '󰀘 '
  RockyLinux = ' '
  SUSE = ' '
  Solus = ' '
  Ubuntu = ' '
  Ultramarine = ' '
  Unknown = ' '
  Uos = ' '
  Void = ' '
  Windows = '󰍲 '
  Zorin = ' '
