name: Hostwriter.app

concurrency:
  group: hostwriter.app/${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/hostwriter.app.yml
      - _/cloud/hostwriter.app/**

defaults:
  run:
    working-directory: _/cloud/hostwriter.app

env:
  ROOT: _/cloud/hostwriter.app

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: 11

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@main
        with:
          channelId: live
          entryPoint: ${{ env.ROOT }}
          firebaseServiceAccount: ${{ secrets.FIREBASE }}
          projectId: bailey-production
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          target: hostwriter
